### ISSUE TITLE
Error "/lib64/libc.so.6: version `GLIBC_2.18' not found"

### ISSUE THREAD

**Issue by halloleo** [patrickomatic/csv-plus-plus#57]
Cool project. Very existing!

However I am running `csvpp` on a Linux system (RHEL 7.9) and I get the following error:

    csvpp: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by csvpp)

`libc.so.6` exists on the system under these paths:

* `/usr/lib/libc.so.6`
* `/usr/lib64/libc.so.6`

Any idea how to get this running?

**Comment by patrickomatic** [comment]
@halloleo are you building from source or using one of the release downloads? I just tested on ubuntu and both of those seem to work for me.

**Comment by patrickomatic** [comment]
[csvpp-v0.6.1-5-g18e09e4-x86_64-unknown-linux-musl.tar.gz](https://github.com/patrickomatic/csv-plus-plus/files/14489621/csvpp-v0.6.1-5-g18e09e4-x86_64-unknown-linux-musl.tar.gz)

@halloleo can you see if this one works?  I think the problem is your system has an outdated glibc, so this is statically built to not need it

**Comment by halloleo** [comment]
Thanks for looing into this.

I didn't built from source -- I just used your release, 

I'll try your static exe. The RHEL system I use is _quite_ outdated indeed...

**Comment by halloleo** [comment]
That's what it was, @patrickomatic! When compiled statically it all works beautifully. Thanks a lot!

**Comment by patrickomatic** [comment]
Great, I'll include statically linked binaries in the releases going forward. Lemme know if you have any other problems
